### ISSUE TITLE
Dubious formatting in Remark 9.4.9

### ISSUE THREAD

**Issue by NieDzejkob** [vEnhance/napkin#100]
Remark 9.4.9 looks like this:

![remark](https://user-images.githubusercontent.com/23580910/95635667-548b1680-0a8d-11eb-9b44-7a06d1c61df5.png)

The combination of an em-dash and bullet on the same line strikes me as odd, and I suspect it happened by accident.

**Comment by vEnhance** [comment]
It's indeed accidental, but the alternative (hanging em-dash leading to nothing) looked pretty silly as well, so I opted for the one that at least took less space. :P
