### ISSUE TITLE
Unmentioned caveat: G/H × H is not necessarily isomorphic to G

### ISSUE THREAD

**Issue by NieDzejkob** [vEnhance/napkin#107]
When you introduce quotient groups, you show some examples of how `×` (the direct product) and `/` behave somewhat like multiplication and division: `(G × H) / G' ≅ H`.

I believe it is quite important to also show the non-examples. As I've realized when I learned of the Schur-Zassenhaus theorem, it is not necessarily the case that `(G/H) × H ≅ G` (Wikipedia has a [nice counter-example](https://en.wikipedia.org/wiki/Schur%E2%80%93Zassenhaus_theorem#Examples) here, take `G = Z/4Z = {0, 1, 2 3}` and `H = <2>`).

**Comment by YodaEmbedding** [comment]
Reference to page 75:

![pg75](https://user-images.githubusercontent.com/721196/100033518-38c6a000-2daf-11eb-9422-0804e3d499e0.png)

----

The question is where would one mention that? As a footnote? The section is titled "Eliminating the homomorphism". (Side note: it also has unusual prototypical example,  `Z/nZ = Z/nZ`, which I think is a bit obvious. :P)

**Comment by 123jimin** [comment]
I'm learning group theory with the Napkin, and I had the same misconception until talking about quotient groups with another person.

I was really confused until working through the counter-example `G = Z/4Z` and `H = Z/2Z` for `(G/H) x H ≅ G` and understanding [this counter-example on Reddit](https://www.reddit.com/r/cheatatmathhomework/comments/13fz03/group_theory_quotient_by_a_subgroup_isomorphic_to/c73mp6k/?utm_source=share&utm_medium=web2x&context=3) for a related (wrong) relationship `(G x H) / H' ≅ G`.

As the parent Reddit comment of the comment I linked says, "The quotient group depends not only on the isomorphism class of H, but on the position of H in G." I think that this should be "the key lesson" when counter-examples are discussed.

**Comment by 123jimin** [comment]
Not directly related to this issue, but I also had a hard time understanding normal subgroups, because the Napkin didn't show me any *non-normal* subgroups when the definition of the normal group was introduced. My first (wrong) intuition was that all subgroups were normal.

Thankfully [Go11](https://gowers.wordpress.com/2011/11/20/normal-subgroups-and-quotient-groups/) referenced in the chapter was very helpful, but I think that the Napkin would be improved a lot by giving an example of subgroup that's not normal.

**Comment by NieDzejkob** [comment]
> I think that the Napkin would be improved a lot by giving an example
> of subgroup that's not normal.

I'd suggest <s> in D_2n.

**Comment by vEnhance** [comment]
Thanks for the suggestions! If someone wants to open a pull request incorporating

* Counterexample to `(G/H) x H ≅ G`
* Example of a non-normal subgroup

Then I'd be very happy to look at it. Otherwise, I will get to it myself eventually, but it could take a few weeks.

**Comment by vEnhance** [comment]
All done!
