### ISSUE TITLE
Minor: typo on page 721 in latest version

### ISSUE THREAD

**Issue by frankthinker** [vEnhance/napkin#114]
In Definition 75.4.1, the second part "Gluing", the sections s_α should be in F(U_α) instead of in (U_α), because s_α are the elements of the local sections.

![image](https://user-images.githubusercontent.com/55730534/106227014-6b639d80-6223-11eb-9c83-3b4776c7984e.png)

**Comment by vEnhance** [comment]
Yep, indeed a typo, I had wrote `\mathscr (U_\alpha)` and left out the F. Thanks for catching that!
