### ISSUE TITLE
Reps of k[x, y] by V require representing operators to commute

### ISSUE THREAD

**Issue by lukasjuhrich** [vEnhance/napkin#125]
In the example about algebra representations, the following is written:

https://github.com/vEnhance/napkin/blob/343bd11fcb0a90b182f166ec3b1dc79a20ee43c3/tex/rep-theory/rep-alg.tex#L208-L211

However to my knowledge, since the polynomial ring `k[x, y]` is commutative, the representing operators `S, T` must commute as well. This should be mentioned.

**Comment by vEnhance** [comment]
Yes. I think in this case I want to write "polynomial ring in two noncommuting variables" rather than "k[x,y]" since a lot of the algebras in the rep theory part aren't commutative. Will think about how to write this in a way that's not too confusing.
