### ISSUE TITLE
File `media/tangent.pdf' not found.

### ISSUE THREAD

**Issue by aDotInTheVoid** [vEnhance/napkin#13]
It apears you have accidentaly `.gitignore`d one of your images.

Invocation: `pdflatex -halt-on-error -interaction=nonstopmode Napkin`

```
LaTeX Warning: File `media/tangent.pdf' not found on input line 73.


! Package pdftex.def Error: File `media/tangent.pdf' not found.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.73 	\includegraphics{media/tangent.pdf}
                                         
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on Napkin.log.
```

[Full log](https://gist.githubusercontent.com/aDotInTheVoid/16b84f362b2332ba91830f3aa1839d0d/raw/117197337c4ea0387e766739371b656a3a560598/log.txt)

**Comment by jzw2** [comment]
`code.pdf` and `earth.pdf` are also missing.

**Comment by vEnhance** [comment]
Thanks for pointing these out. Should be fixed now (please let me know if not).
