### ISSUE TITLE
Are we missing a letter? (can make a PR)

### ISSUE THREAD

**Issue by fzyzcjy** [vEnhance/napkin#131]
By the matrix multiplication I know, it seems that the second formula lacks coefficient `x_k`.

https://github.com/vEnhance/napkin/blob/main/tex/quantum/shor.tex#L92-L96

![image](https://user-images.githubusercontent.com/5236035/146393700-374219fd-31bb-4fa3-91fb-cff08927b3b2.png)

**Comment by vEnhance** [comment]
Yep, you're correct. If you submit a PR I would be happy to merge it.

**Comment by fzyzcjy** [comment]
Sure

**Comment by fzyzcjy** [comment]
pr done
