### ISSUE TITLE
Adding hyperlinks to chapters in advised reading graph.

### ISSUE THREAD

**Issue by stampyzfanz** [vEnhance/napkin#142]
In page 9 of the pdf or ix, _Advice for the reader_, _Deciding what to read_ there is a graph of what topics and chapters are prerequisites to other topics and chapters. I tried to click to go to the _Calc_ topic and noticed that it was just text. I suggest that it links to the first page in the range of chapters in the topic.
![image](https://user-images.githubusercontent.com/34364128/153682249-d7f48244-3159-4cb2-8fc4-eac92644edc1.png)
The relevant code should be `tex/frontmatter/digraph.tex`.

**Comment by chennisden** [comment]
Besides `Grp Classif` all of these ranges begin on the first chapter of a part. Would you like me to
- just `\label` the chapter `Group Classifications` and hyperref to the part labels for the rest, or
- make appropriate labels for each chapter & hyperref there?

**Comment by user202729** [comment]
Shouldn't this issue be closed now? The relevant pull request is already merged.
