### ISSUE TITLE
Make use of git tags and github releases

### ISSUE THREAD

**Issue by jvoisin** [vEnhance/napkin#150]
The readme says "Napkin v1.5", but the [tags](https://github.com/vEnhance/napkin/tags) and [releases](https://github.com/vEnhance/napkin/releases) sections are empty.

It would be nice to do actual releases :)

**Comment by vEnhance** [comment]
I think this would make sense if I got to actively writing the text again. Unfortunately for the past years I haven't found the energy to do so and most of the commits are just typo fixes and the like, so I think in that case it makes less sense to try and apply tags at the moment.

**Comment by jvoisin** [comment]
Then it would be nice to tag a `1.0` to signal that the document has reached *stability*.

**Comment by vEnhance** [comment]
@Incompleteusern once #210 is merged maybe we can tag that as v1.5?

**Comment by vEnhance** [comment]
ac242e7 was tagged v1.5.

Will bump to v1.6 if new chapters or significant new content is introduced.
