### ISSUE TITLE
Theorem 29.4.5 is broken

### ISSUE THREAD

**Issue by vEnhance** [vEnhance/napkin#162]
See e.g. https://mathoverflow.net/questions/81613/non-analytic-function-with-convergent-taylor-series-everywhere

 I forget what I meant to write

**Comment by user202729** [comment]
I think one way to fix the theorem is "f: U → ℝ **described** by a power series at a point p will be analytic on U". (since it's not obvious to me, I'd point out that the theorem remains nontrivial, because given the information f is described by a power series at p, we only trivially know that f is analytic at p)

**Comment by vEnhance** [comment]
I'm now reading the mathoverflow link again a few years later and now more confused. The comments seems to say:

>  You can use the Baire category theorem to show that there are no non-analytic functions with a Taylor series with positive radius of convergence everywhere. 
>  This is also stated in Dave L Renfro's first link above. See the part where it says "...Therefore, it is not possible to have an example in which every point is a (C)-point." 

What exactly was the bug with Theorem 29.4.5 again? Reading the quotes I thought this was what I wanted.

**Comment by user202729** [comment]
I think we just consider the example right above.

![image](https://github.com/vEnhance/napkin/assets/25191436/76efb93d-c8d4-4477-a310-1a666f8b59d8)

for every point p ∈ U, its Taylor series has positive radius of convergence, yet the function is not analytic.

**Comment by vEnhance** [comment]
Ah... So then why isn't the comment I quoted wrong? Is the intention that the function has to actually coincide with the Taylor series at some point p for points q \neq p and we're measuring the radius of convergence at q?

(Also, is there a point to keeping the theorem? I think I was including it because I wanted to use it to get that sin(x) was analytic. That's kind of a moot point now because you can't detect the function is analytic from just knowing all the derivatives at any particular point.)

**Comment by user202729** [comment]
Hm... if we don't have that, how can we prove anything at all is analytic? I think the point of that theorem is to prove the exp function is analytic from the definition in the section below.

We can also show sin(x) is analytic if we "take for granted" that it's defined by/coincides with the power series. But of course it's a moot point without a rigorous algebraic definition of sin(⋅).

I think [my proposed edit] should be rephrased as "power series are analytic (inside their radius of convergence)".

**Comment by vEnhance** [comment]
OK, yeah, that makes sense. I'll make an edit to that effect.

**Comment by user202729** [comment]
Looks good. Minor typo: the two `(-R,R)` should be `(p-R,p+R)` I think.
