### ISSUE TITLE
Can someone define $f$ in this context?

### ISSUE THREAD

**Issue by JacobHA** [vEnhance/napkin#168]
https://github.com/vEnhance/napkin/blob/1114f569ccdc84c20572b08274e8f6612eea44c2/tex/linalg/dual-trace.tex#L457

**Comment by JacobHA** [comment]
If it borrows from the previous section's use, maybe a reminder would be nice 😄

**Comment by vEnhance** [comment]
I think $f$ is just any element of $V^\vee$.
