### ISSUE TITLE
Minor error constructing outer measures from pre-measures

### ISSUE THREAD

**Issue by JesseSilverberg** [vEnhance/napkin#172]
https://github.com/vEnhance/napkin/blob/main/tex/measure/caratheodory.tex#L215-L217

The construction linked above isn't quite sufficient to force the $B_n$ to be disjoint. Instead, the line $B_3 = (A \cap A_3) \setminus B_2$ should read $B_3 = (A \cap A_3) \setminus (B_2 \cup B_1)$.

**Comment by vEnhance** [comment]
Thanks!
