### ISSUE TITLE
Reference broken (missing) and Possible Typos

### ISSUE THREAD

**Issue by sleepymalc** [vEnhance/napkin#174]
I have noticed something when reading it:
1. For problem 1A., the figure's source [Ge] "Topological Girl’s Generation. Topological Girl’s Generation. url: https: //topologicalgirlsgeneration.tumblr.com/." is dead.
2. In Example 4.4.4 (b), the phrase is weird: it should be "which we will usually denote" or something like that.

**Comment by vEnhance** [comment]
Unfortunately I don’t know if there’s an updated link anywhere. I do
remember looking before a long time ago (it used to be Napkin had a lot of
memes from TGG, back when I was still a teenager).--
*Evan Chen (陳誼廷) *[via evanchen at mit.edu]
https://web.evanchen.cc/

**Comment by vEnhance** [comment]
Fixed the typo in 4.4.4(b).
