### ISSUE TITLE
Theorem 19.5.7 bug?

### ISSUE THREAD

**Issue by suhailsherif** [vEnhance/napkin#177]
This is about Schur's lemma for algebraically closed fields. As stated it claims if V is an irrrep, then any intertwining from V to V must be a scalar multiplication. However this seems to only be true if the intertwining is from V to V where we're considering the same representation in the domain and image. The "same representation" condition is not mentioned.

https://github.com/vEnhance/napkin/blob/90cd09947af7ec53138a88b44a31cf4cc40ddd8a/tex/rep-theory/rep-alg.tex#LL470C1-L476C14

**Comment by vEnhance** [comment]
> However this seems to only be true if the intertwining is from V to V where we're considering the same representation in the domain and image.

I believe this is packaged in the definition. An irrep is a vector space _together with the representation on it_. In other words, as explained in, Abuse of Notation 19.2.3, the single symbol "V" is meant to encode the action as well.

If for some reason I wanted to consider two diffrent actions, I would probably write it explicitly as `(V, \rho_1)` and `(V, \rho_2)` or similar.

If you have suggestions for how to make this more clear, please submit a pull request. Or, if there is any chance I misunderstood the issue, please re-open.
