### ISSUE TITLE
Inconsistent notation: |G/H| and [G:H]

### ISSUE THREAD

**Issue by user202729** [vEnhance/napkin#211]
For G and H groups, I notice two different notations being used:

* sometimes |G/H| is used:
 
![image](https://github.com/vEnhance/napkin/assets/25191436/cf893785-aed2-4f47-8f09-315dfe51f131)

* some other times, [G:H] is used:

![image](https://github.com/vEnhance/napkin/assets/25191436/61d39258-13d1-4f81-9158-5248a1f5de12)

(the latter notation is also used for the degree of a field extension however.)

Is there some reason behind this, or should it be cleaned up (in the latter case which one do you prefer?)

**Comment by vEnhance** [comment]
Do we ever actually define $[G:H]$? If not maybe we can just switch to $|G/H|$ always for groups (and continue using $[K:F]$ for field extensions).

**Comment by user202729** [comment]
Evidently seem not.
