### ISSUE TITLE
Use the normal arrow ends for surjective arrows?

### ISSUE THREAD

**Issue by user202729** [vEnhance/napkin#215]
For some reasons, the current surjective arrows in commutative diagrams feel kind of weird.

![image](https://github.com/vEnhance/napkin/assets/25191436/9701df11-9b13-40e5-b49d-655f09f83c26)

For comparison, the `\surjto` macro uses the normal arrow.

![image](https://github.com/vEnhance/napkin/assets/25191436/642b9053-7cbd-4e21-a1fc-11d270c9572e)

What do you think?

(to get the normal arrow, I think we can do something like

```
\tikzset{
	surjective/.style={
		>={Computer Modern Rightarrow}, commutative diagrams/two heads
	}
}
```

then use `surjective` instead of `two heads` in the actual diagrams.)

Or maybe it's also possible to shorten the lengths like (look at the `C ↠ D` arrow):

![image](https://github.com/vEnhance/napkin/assets/25191436/a0284674-6e9f-42e4-bfff-80ff653ff809)

(produced by

```
\tikzset{
	surjective arrow /.tip = {tikzcd to[sep=-1.5pt]tikzcd to},
	surjective/.style={
		-surjective arrow
	}
}
```

)

**Comment by vEnhance** [comment]
iirc i had an issue with the "default" tikz-cd arrows where the usual arrows were hard to see in some PDF viewers, so i switched to the filled arrow tips with black triangles.

the latter approach seems reasoanble though
