### ISSUE TITLE
Terminology: "maximal"?

### ISSUE THREAD

**Issue by user202729** [vEnhance/napkin#223]
I feel that the Napkin uses a nonstandard terminology with "maximal", e.g.

![image](https://github.com/vEnhance/napkin/assets/25191436/b97a125f-36f2-4714-8670-d6939c3381c5)

![image](https://github.com/vEnhance/napkin/assets/25191436/621480eb-d89e-4c5c-a87b-49c263ded9eb)

i.e. it uses "maximal" to mean "maximum", except in "maximal ideal" which indeed mean "locally maximum ideal" i.e. "proper ideals that is not contained in any other proper ideals". The standard meaning of maximal should indeed be "locally maximum".

**Comment by vEnhance** [comment]
I think I should probably just never use the term "maximal element" to avoid confusion.

Is this specifically just for posets? Or other places too?

**Comment by user202729** [comment]
As far as I can see there's only these 5 usages in set-theory, which is only for poset.

```
set-theory/forcing.tex:Let $\Po = (\Po, \le) \in M$ be a poset with a maximal element $1_\Po$
set-theory/forcing.tex:         \ii The maximal element $1_\Po$ is the empty string $\varnothing$.
set-theory/forcing.tex:         \ii The maximal element $1_\Po$ is $1$.
set-theory/CH.tex:      What is the maximal element $1_\Po$ here?
set-theory/CH.tex:      For each $x \in X$, we can consider (using the Axiom of Choice) a maximal st
```

There's a few other occurrences that use the standard meaning of maximal.

```
set-theory/CH.tex:      (in fact maximal by inclusion).
set-theory/CH.tex:      For each $x \in X$, we can consider (using the Axiom of Choice) a maximal st
set-theory/zorn-lemma.tex:      Prove that there exists a maximal set $Y \in \mathcal F$
```

The rest only use maximal as in maximal ideal.

**Comment by vEnhance** [comment]
Merging of #224 should close this now.
