### ISSUE TITLE
Automatically pull out all footnotes?

### ISSUE THREAD

**Issue by user202729** [vEnhance/napkin#226]
Is it a good idea? e.g. with

```
\usepackage{footnote}
\makesavenoteenv{example}
```

etc. (it might also be a good idea to figure out how to get the numbering to be consistent in that case.

I think there's a few instances of `\footnote` being used in a `example` box etc., which leads to the footnote being put inside the box e.g. the part about reduced homology groups. In my pull requests, I tend to manually manage `footnotemark` and `footnotetext`.

------

Actually, this has a little problem that if a box is broken onto two pages, then all the footnote will be on the page that contains the last page, but I don't see any obvious way to fix this.)

**Comment by vEnhance** [comment]
I don't personally mind having the footnote inside the example box, but don't really have a strong opinion either way. I think the main thing is to be consistent.

**Comment by user202729** [comment]
Apparently I have been manually pulling these out... guess I should refactor it.
