### ISSUE TITLE
Need to add \ for fraction

### ISSUE THREAD

**Issue by Shishir1729** [vEnhance/napkin#228]
https://github.com/vEnhance/napkin/blame/13c4dda36139fc093fc5270d960c1a152dc66430/tex/complex-ana/meromorphic.tex#L379C5-L379C5

**Comment by user202729** [comment]
I caught it in 602a8205c096c5acf305d938373f65e06e29776d and included it in #225, but bundling it together with a 5000-line worth of changes isn't exactly a way to get it reviewed any time soon.
