### ISSUE TITLE
Typo in example 54.1.6 (page 522, Algebric NT I)

### ISSUE THREAD

**Issue by Nimrod-S** [vEnhance/napkin#230]
The example claims alpha is a member of Q[sqrt(3)]. If I understand the example correctly, it's probably supposed to be a member of Q[cube root(2)]. The field written right now does not agree with the claim that K has degree 3.

**Comment by user202729** [comment]
(This one is my fault, sorry.)

**Comment by vEnhance** [comment]
You're right! Will fix momentarily.
