### ISSUE TITLE
Pullback formula 

### ISSUE THREAD

**Issue by jfab20** [vEnhance/napkin#246]
I think there is a mistake in the pullback formula when expanding with bases.
![image](https://github.com/user-attachments/assets/e0a889ab-11e6-4ff5-817f-3296393ba452)

The point is that when computing the pullback you take the original expression of the form and substitute each $dx_i$ with $d\phi_i$. So you should not change the index from $J$ to $I$. You can see an example of this in "Introduction to Smooth Manifolds" by Lee: 
![image](https://github.com/user-attachments/assets/c741b81d-2e28-48e1-b5da-8da54e9b5f2e)
This is also done in "Manifolds and Differential Forms" from Reyer Sjmaar: 
![image](https://github.com/user-attachments/assets/e3c35001-2510-4d5d-bfcc-add189e22d21)
![image](https://github.com/user-attachments/assets/fb82051e-78a6-487f-96a8-b175c848ebb5)

**Comment by user202729** [comment]
Looks correct.

For consistency of notation the first one should probably be written as `dw_J` as well.

**Comment by jfab20** [comment]
> Looks correct (the second one should also be `⊆ {1, …, n}`).
> 
> For consistency of notation the first one should probably be written as `dw_J` as well.

The $dw_J$ part I already pointed out on discord. It has been corrected to $w_J^\vee$ although I agree that it would look better as $dw_J$

**Comment by vEnhance** [comment]
Thanks, pushed a fix. If you could check 0b7acc3 does the right thing that'd be appreciated. If I messed up yet again please re-open or comment.
