### ISSUE TITLE
Boundary of disk 

### ISSUE THREAD

**Issue by jfab20** [vEnhance/napkin#247]
Based on the picture I guess it should say $c: [0,1]^2\to \mathbb{R}^2$. Also the map $c$ is all messed up, I think it should be  $(r,\theta) \to (r \cos (2 \pi \theta), r \sin(2 \pi \theta))$ 
![image](https://github.com/user-attachments/assets/b7a32cee-ab2b-4a3e-bc81-2394ba658828)

**Comment by user202729** [comment]
Sounds correct (though because 𝐞₁ represents the vector I guess it could be written as (r, θ) ↦ r cos(2π θ) 𝐞₁ + r sin(2π θ) 𝐞₂).

**Comment by vEnhance** [comment]
Thanks, pushed a fix. If you could check 068b4ec does the right thing that'd be appreciated. If I messed up yet again please re-open.

**Comment by jfab20** [comment]
> Thanks, pushed a fix. If you could check [068b4ec](https://github.com/vEnhance/napkin/commit/068b4ecb0b727e048af1fb0b44c578779c49bc09) does the right thing that'd be appreciated. If I messed up yet again please re-open or comment.

Not quite, you should change $t \to \theta$ as well. 

It should be 

```latex
c \colon [0,1] \times [0,1] \to \RR^2 \quad\text{by}\quad
	(r,\theta) \mapsto r\cos(2\pi \theta)\ee_1 + r\sin(2\pi \theta)\ee_2.
```
