### ISSUE TITLE
Haar Measure Properties Typo (p. 414)

### ISSUE THREAD

**Issue by pr4-kp** [vEnhance/napkin#260]
<img width="1041" alt="Screenshot 2024-12-25 at 2 53 42 AM" src="https://github.com/user-attachments/assets/e477c3f6-a096-4381-9343-cebe466f698c" />

The fourth property should be 

$$\mu(U) = \sup\\{\mu(K) : K \subseteq U, K \text{ compact} \\}$$ 

(assuming the property is inner regularity).

**Comment by vEnhance** [comment]
Thanks for catching that.
