### ISSUE TITLE
Limit chapter typos

### ISSUE THREAD

**Issue by Element118** [vEnhance/napkin#45]
Silly example of monotonicity has typos: spelling of monotonicitiy as well as the sequence provided is not monotonic.
https://github.com/vEnhance/napkin/blob/master/tex/calculus/limits.tex

Partial sums of nonnegatives bounded implies convergent
... sequence s_n converges to M=sup_n s_n
but M is just an upper bound for the sequence.

**Comment by vEnhance** [comment]
I'll fix the typo. You're also right about the terms being goofed up; it should start 1.2, 1.24, etc.

Also, you are right I should use a different letter for \sup_n s_n since it is not the original upper bound M. I'll rename it to L = \sup_n s_n and then I think the proof should be okay after that (once I change all the M's to L's).

**Comment by Element118** [comment]
"but since the sequence is monotic"
Line 491, should be "monotonic"?

**Comment by vEnhance** [comment]
Yep, thanks will fix! Let me know if you see anything else.

**Comment by Element118** [comment]
I decided to read it critically.
I noticed:
Exercise 26.3.7. Show that this definition makes sense, by checking that the supremums
are non-decreasing, and bounded above.
The supremums are actually non-increasing. I think you should say the sequence is bounded (above and below here)
For example consider:
lim sup of -1, -2, -3, -4, -5...

Here at line 491
once $s_n \ge L-\eps$
for some $N$ then $s_{n'} \ge L-\eps$ for all $n \ge n'$.
maybe it can be better written as (the inequality was the wrong way round)
once $s_n \ge L-\eps$ then $s_{n'} \ge L-\eps$ for all $n' \ge n$.

Line 544:
We will show that sum partial sums of $b_n$
Replace with
We will show that the partial sums of $b_n$

Line 656:
However, if we change the definition so that $f(0) = 0$ instead,
	then $f$ becomes continuous.
Maybe say "then $f$ becomes continuous at 0."

That should be all for this chapter.

**Comment by vEnhance** [comment]
Thank you kindly for these corrections. I'll fix them. Marking this as closed, but please feel free to re-open (or open new issues) if you spot anything else.
