### ISSUE TITLE
Weird Sentence in Chapter 20 intro

### ISSUE THREAD

**Issue by ELanning** [vEnhance/napkin#48]
![image](https://user-images.githubusercontent.com/38930062/69770899-934b0300-113f-11ea-8ca1-5c15ea4e9475.png)

should this be "they exhibit the good property _then_ we just have to figure out ..." instead of that? The whole sentence feels pretty clunky to me.

**Comment by vEnhance** [comment]
I'll just remove the whole blob "they exhibit the good property". That way the sentence read

> So when we study finite-dimensional representations of semisimple algebras $A$, we just have to figure out what the irreps are, and then piecing them together will give all the representations of $A$.

Cleaner this way.
