### ISSUE TITLE
Too much just

### ISSUE THREAD

**Issue by ELanning** [vEnhance/napkin#49]
![image](https://user-images.githubusercontent.com/38930062/69771003-09e80080-1140-11ea-829a-edf42ebe8dc3.png)

I love this book, but the _just_ count could be culled a bit

**Comment by vEnhance** [comment]
I decided to remove some of the "just" uses from the chapters with the most, but I didn't have enough patience to go through all 60+ chapters taking out ones I deemed unnecessary, and doubt I will soon. I will keep this in mind in the future though as I write more chapters.
