### ISSUE TITLE
Cycle decomposition notation

### ISSUE THREAD

**Issue by NieDzejkob** [vEnhance/napkin#51]
The solution sketch of problem 1C is using what I now know to be the cycle notation for permutations. However, I stumbled upon this by accident - I haven't encountered this notation beforehand, which made the solution sketch really confusing. I also haven't been able to find the notation in the notation glossary.

**Comment by vEnhance** [comment]
Thanks for the suggestion. You're right that it would be better if I defined cycle notation (which is used a couple other places), but since it's sort of a isolated combinatorics definition I can't think of a good place to squeeze it in. My inclination right now is 6.(ii) of the preface, but I'm open to other suggestions too.

**Comment by NieDzejkob** [comment]
On Sat, Nov 30, 2019 at 05:09:53PM -0800, Evan Chen wrote:
> Thanks for the suggestion. You're right that it would be better if I defined cycle notation (which is used a couple other places), but since it's sort of a isolated combinatorics definition I can't think of a good place to squeeze it in. My inclination right now is 6.(ii) of the preface, but I'm open to other suggestions too.

That sounds reasonable to me. I would make sure that it comes before the
"remarks for experts" parts. This order is mostly respected already, but
I find it somewhat weird that $0 \notin \mathbb N$ is 'hidden' between
the specifics of rings and the axiom of choice.

**Comment by vEnhance** [comment]
This is resolved in https://github.com/vEnhance/napkin/commit/49e5d76e697b6324d153927545a6c0cf8f98f708 now. Feel free to re-open if I botched anything.
