### ISSUE TITLE
Exercise about ideals before the definition of ideals

### ISSUE THREAD

**Issue by NieDzejkob** [vEnhance/napkin#60]
In Exercise 4.4.5, you ask the reader to prove that all fields have two ideals. However, this is before ideals are defined, and as a consequence, one cannot possibly know how to solve this yet.

**Comment by vEnhance** [comment]
Thanks. This should be fixed in https://github.com/vEnhance/napkin/commit/68e7e08224cef04ddaa976445f9dd89a7d5d2314.

**Comment by NieDzejkob** [comment]
On Fri, Jan 10, 2020 at 05:45:07PM -0800, Evan Chen wrote:
> Thanks. This should be fixed in https://github.com/vEnhance/napkin/commit/68e7e08224cef04ddaa976445f9dd89a7d5d2314.
Yes, this is fixed now, though while looking at the diff, I noticed that
the prototypical example for the homomorphisms section also mentions
ideals, which could be a related issue?

**Comment by vEnhance** [comment]
Yes, that's indeed a different issue. It should be fixed in https://github.com/vEnhance/napkin/commit/c5d50944a547eee9316833257b84d2fc85358e48.
