### ISSUE TITLE
Change visual style of hyperlinks

### ISSUE THREAD

**Issue by mkesper** [vEnhance/napkin#73]
Wouldn't it be nice to change the appearance of hyperlinks to something less intrusive?
Maybe use colorlinks instead?
Like shown here: https://tex.stackexchange.com/questions/823/remove-ugly-borders-around-clickable-cross-references-and-hyperlinks

**Comment by vEnhance** [comment]
Thanks for the suggestion. This is implemented now in 7a96cf1f08b56bd3298cfce0073a3593ac03392e.
