### ISSUE TITLE
Rasiowa-Sikorski lemma

### ISSUE THREAD

**Issue by puzzlet** [vEnhance/napkin#75]
![image](https://user-images.githubusercontent.com/787236/80608071-3f877180-8a71-11ea-9aa6-2524be508b35.png)

The original Rasiowa-Sikorski lemma demands the family of dense subsets to be countable. It seems that _Napkin_ also assumes it ("hit them one by one") but are we sure that the family of all dense sets of **P** is countable if the model **M** is countable?

**Comment by vEnhance** [comment]
The dense sets we are trying to hit are required to also be elements of $M$, and $M$ is itself countable. Does that work?

**Comment by puzzlet** [comment]
> The dense sets we are trying to hit are required to also be elements of $M$,

I didn't see that was in the definition of _M-generic_. Thanks!
