### ISSUE TITLE
Consider adding a license and/or CLA

### ISSUE THREAD

**Issue by jlebar** [vEnhance/napkin#77]
Hi, I've been enjoying going through your book while sheltering in place.  Thanks so much for the work you've put into it.

I noticed there isn't an explicit license for this book (that I can find).  IANAL but I've worked a lot in open-source software, including on licensing, so take this unsolicited advice (that you may already be aware of) for what it's worth.

In the absence of an agreement otherwise, when I send you a PR, I retain copyright over my contribution.  If the contribution is "meaningful", then I can assert rights over that contribution, like preventing you from publishing a book which contains it, or like demanding that you stop distributing a work which contains that contribution online.

A contributor license agreement (CLA) would basically say, in order to send me a PR, you need to give me (Evan) the rights to your work.  So I can do whatever I want with it in the future.  (I guess, you could have a CLA which says something else, but that's what most CLAs say.)

Alternatively or in addition, you could add a license to the work.  If you don't have a CLA, this would say, I (Evan) agree to let anyone use this work under X terms, and by contributing, you retain copyright, and you also agree to let anyone use this work under the same terms.

If you had a license plus a CLA, this would mean, I agree to let anyone use the current version of this work under X terms.  I can't revoke the terms (that's part of most licenses anyway), but I might decide to change the terms for future versions, or add a new license that you could choose to use the old versions under.  Those are things I can do because I own the copyright for the whole thing.

Making either of these changes is unfortunately work, because you'd have to go back in time and get everyone who has contributed to the book to agree to the license and/or CLA.  But they're also easier to do earlier than later.

One other wrinkle: I notice that there are two GPL'ed tex packages in the repository.  This is now slightly more speculation on my part, but I suspect that this means that the whole book is covered under the GPL.  That has all sorts of fun consequences.

Anyway, I don't mean to punish a good deed.  Hope you're staying safe and healthy, and thanks again for your book.

**Comment by vEnhance** [comment]
Thanks for your input! 

Based on what you wrote, my inclination is to just license the book under GPL.  I'm happy to omit a CLA on the basis that, I actually think if someone makes a meaningful contribution to Napkin, e.g. writing a chapter for me, they _should_ be allowed to keep the rights to that chapter. 

Anyway, as far as I know, no one has (yet) made a meaningful contribution to the book itself --- the thing that comes closest might be #17 where @aDotInTheVoid had helped me set up Travis CI. I'll check if he has any objections to having the `.travis.yml` thrown in with the GPL and then go forward with that.

**Comment by aDotInTheVoid** [comment]
No objections, happy for you to do it under any GPL

**Comment by aDotInTheVoid** [comment]
You'll probably also want to mension that `diagrams.sty` isn't gpl

**Comment by vEnhance** [comment]
Agh, right. I've been honestly meaning to eliminate altogether `diagrams.sty` and use `tikz-cd` everywhere instead because it causes issues in quite a few ways (closed source, has time bomb, etc.).

I guess it's finally time.

**Comment by mikepierce** [comment]
@vEnhance  Are you going to take care of the `diagrams.sty` to `tikz-cd` conversion yourself, or make it an issue for someone else to tackle? ;) How many diagrams are there?

**Comment by vEnhance** [comment]
Seems to be 73 diagrams left. I did a bunch last week, and then promptly punted it to June on my to-do list because it was such a chore :)

If anyone here wants to convert any number of diagrams for me, please be my guest! Just file a pull request and reference this issue. I probably won't get to converting more until mid-June at earliest.

**Comment by YodaEmbedding** [comment]
I won't mind doing some diagram conversions after this semester ends. I wanted some more practice with these anyways. :P

**Comment by cirosantilli** [comment]
Why not license text under CC By-SA and GPL only for tex code? CC By-SA is generally more suited for content, and GPL for code. And CC By-SA would be compatible with Wikipedia.

**Comment by vEnhance** [comment]
> Why not license text under CC By-SA and GPL only for tex code?

Thanks for the suggestion. That sounds like a good idea, I'll probably follow this advice. (Once I finally finishing getting rid of `diagrams.sty`, anyways --- but that's a long ways off.)

**Comment by vEnhance** [comment]
With `diagrams.sty` finally removed, the license is up now: https://github.com/vEnhance/napkin/blob/main/LICENSE.mkd

Thanks everyone for the advice.
