### ISSUE TITLE
Compilation Error: Cannot determine size of graphic

### ISSUE THREAD

**Issue by mikepierce** [vEnhance/napkin#81]
The exact error is:

    ! LaTeX Error: Cannot determine size of graphic in media/kofi4.png (no Bounding Box).

    See the LaTeX manual or LaTeX Companion for explanation.
    Type  H <return>  for immediate help.
     ...                                              
                                                  
    l.18 ...ludegraphics[width=32ex]{media/kofi4.png}}

I think this isn't a big deal based on [this TeX.SE post](https://tex.stackexchange.com/q/17734/52612). I wanted to ask here if it's even worth fixing. Like, I think I'm only experiencing this because I'm using [TeXLive](https://tug.org/texlive/), and so using `latexmk` compiles to DVI by default. Compiling with `latexmk -pdf` works fine without errors. Or specifying `$pdf_mode=1` in the `latexmkrc` file works too.

**Comment by vEnhance** [comment]
I added `$pdf_mode=1;` in 0c4f8cb.
