### ISSUE TITLE
Answer to 5F seems to have a counterexample

### ISSUE THREAD

**Issue by rspeer** [vEnhance/napkin#93]
I may be wrong about something, as I'm pretty lapsed in math and keeping up with this book the best I can.

I was surprised by the answer to the second part of 5F, the prime ideals of the real numbers, which seemed to kind of come out of nowhere without explanation. I tried to look up more about it, particularly the case of (x^2 - ax + b) when that quadratic has "two conjugate real roots".

Was this supposed to say "two conjugate non-real roots"?

I found [this topic](https://math.stackexchange.com/questions/3321815/example-of-prime-ideals-in-mathbbrx) on Math Overflow, which says that (x^2 + 1) is prime, because ℝ[x]/(x^2 + 1) is ℂ. The roots of (x^2 + 1) are ±i, which are not real.

**Comment by vEnhance** [comment]
You are correct. It's a typo and should say "conjugate non-real roots".

**Comment by vEnhance** [comment]
Fixed in 0112d94ab6013f0dddc77b8f01bac219ffce4235.
