### ISSUE TITLE
Cant find appendix

### ISSUE THREAD

**Issue by Uzay-G** [vEnhance/napkin#94]
Hi, this is probably a very dumb question, but I can't seem to find the appendix for the book.

I've searched through the book contents,  through this code and looked online to no avail. An appendix is mentioned, but doesn't seem to be provided.

**Comment by vEnhance** [comment]
The appendix just refers to the "Backmatter" part XXIII starting from page 849. (So, I suppose maybe it would be better to call the part "Appendices".)

**Comment by vEnhance** [comment]
Now changed in https://github.com/vEnhance/napkin/commit/35ce5b2b31429a49120a6ba9a8bba7262ca2a9bd
